name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
          pip install ruff

      - name: Linting the code with ruff
        run: |
          ruff check .

      - name: Test with pytest
        run: |
          python -m pytest test

      - name: Get image tags
        id: vars
        run: |
          VERSION=$(grep -oP 'version = "\K[^"]+' ./pyproject.toml)
          echo "VERSION=0.0.1" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag eaton:${VERSION}
          echo "Docker image eaton:${VERSION} built successfully"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: eaton:${VERSION}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
